### PR TITLE
Support unary minus.

### PR DESCRIPTION
**Pull request by hiroxy**
Hi @soniah 

I've enhanced the library to support unary minus.
If this enhancement has worth for the library, could you review the code and merge it into master?

### CODE REVIEW

**Comment by soniah** [comment]
Thanks very much Hiroshi, I'll have a look over the weekend!

**Comment by soniah** [comment]
Thanks @hiroxy I've merged. I've also updated with a travis build :-)

**Comment by codedance** [comment]
Hi @soniah .  Hiroshi works with me at PaperCut.  Thanks very much for your quick action as usual. :-)

If you're ever in Melbourne, please let me know.

**Comment by soniah** [comment]
:+1:  :)

**Pull request merged**
